In [2]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten,Conv2D,MaxPooling2D

In [3]:
import pandas as pd
import numpy as np

In [4]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [7]:
Y_train=train['label']
del train['label']

In [9]:
X_train=train.values
X_test=test.values

In [11]:
print(X_train.shape)
print(X_test.shape)

(42000, 784)
(28000, 784)


In [21]:
X_train=X_train.reshape(42000,28,28,1)
X_test=X_test.reshape(28000,28,28,1)
print(X_train.shape)
print(X_test.shape)

(42000, 28, 28, 1)
(28000, 28, 28, 1)


In [16]:
from keras.utils import to_categorical
num_classes = 10
Y_train = to_categorical(Y_train,num_classes)

In [18]:
import matplotlib.pyplot as plt

In [27]:
model=Sequential()
##
conv1=Conv2D(32, (3,3), padding='same',activation='relu', input_shape =X_train.shape[1:])
model.add(conv1)
conv1_pool=MaxPooling2D(pool_size=(2,2))
model.add(conv1_pool)
conv1_dropout=Dropout(0.2)
model.add(conv1_dropout)

conv2=Conv2D(64,(3,3),activation='relu',padding='same')
model.add(conv2)
conv2_pool=MaxPooling2D(pool_size=(2,2))
model.add(conv2_pool)
conv2_dropout=Dropout(0.2)
model.add(conv2_dropout)

model.add(Flatten())

hidden_layer1=Dense(units=256,activation='relu')
model.add(hidden_layer1)
hidden_layer1_dropout=Dropout(0.2)
model.add(hidden_layer1_dropout)

hidden_layer2=Dense(units=128,activation='relu')
model.add(hidden_layer2)
hidden_layer2_dropout=Dropout(0.2)
model.add(hidden_layer2_dropout)

output_layer=Dense(units=num_classes,activation='softmax')
model.add(output_layer)

In [28]:
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 28, 28, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 14, 14, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 7, 7, 64)          0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 7, 7, 64)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 3136)              0         
__________

In [29]:
batch_size=64
epochs=10

In [32]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255.0
X_test /= 255.0

In [33]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [36]:
##model.fit(X_train,Y_train,batch_size=batch_size,verbose=0,epochs=epochs)

In [37]:
from keras.models import load_model

In [40]:
new_model=load_model('mnist_model.h5')

In [43]:
print(new_model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 28, 28, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 14, 14, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 7, 7, 64)          0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 7, 7, 64)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 3136)              0         
__________

In [44]:
new_model.fit(X_train,Y_train,batch_size=batch_size,epochs=1)

Epoch 1/1
42000/42000 [==============================] - 33s 781us/step - loss: 0.0148 - acc: 0.9965


In [45]:
Y_pred=new_model.predict(X_test)

In [46]:
Y_pred

array([[1.52521384e-22, 1.25447332e-21, 1.00000000e+00, ...,
        1.06593838e-20, 6.75328715e-17, 2.06384083e-20],
       [1.00000000e+00, 2.78877093e-29, 1.05623255e-19, ...,
        4.26936930e-29, 4.09389812e-20, 1.46412849e-22],
       [3.88824340e-27, 3.16218562e-24, 4.76293586e-21, ...,
        1.06964046e-21, 5.02185559e-16, 1.00000000e+00],
       ...,
       [3.10023319e-30, 2.69467630e-18, 4.31390432e-19, ...,
        1.04648729e-18, 1.55478316e-18, 3.94339729e-17],
       [4.32111591e-20, 5.56840204e-18, 6.48168140e-16, ...,
        1.05560685e-14, 2.88859887e-12, 1.00000000e+00],
       [1.54546897e-19, 1.27509230e-16, 1.00000000e+00, ...,
        1.39908005e-16, 4.24595092e-13, 2.20227124e-16]], dtype=float32)

In [49]:
Y_pred_mnist = np.argmax(Y_pred, axis=1) # assuming you have n-by-5 class_prob

In [48]:
Y_pred_mnist

array([2, 0, 9, ..., 3, 9, 2])

In [50]:
df_ans=pd.DataFrame(Y_pred_mnist)

In [58]:
image_id=np.arange(X_test.shape[0])

In [83]:
image_id=np.append(image_id,[28000])

In [84]:
image_id

array([    1,     2,     3, ..., 27998, 27999, 28000])

In [85]:
df=pd.DataFrame(image_id)

In [86]:
Y_pred_mnist.shape

(28000,)

In [87]:
df['label']=Y_pred_mnist

In [90]:
df.shape

(28000, 2)

In [95]:
df.rename(columns={"ImageId":"0"},inplace=True)

In [97]:
df.columns

Index([0, 'label'], dtype='object')

In [98]:
coulmns=["ImageId","Label"]

In [99]:
df.columns=coulmns

In [101]:
df.to_csv('Y_pred_final.csv', encoding='utf-8', index=False)